{% set version = "4.3.4" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-multinet
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/multinet_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/multinet/multinet_{{ version }}.tar.gz
  sha256: 732128032fb9d2ef6b04d9577553eb08b5dbe7078a3681b1c4a53f0edb07039a

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcolorbrewer
    - r-rcpp >=1.0
    - r-igraph >=2.2.2
  run:
    - r-base
    - r-rcolorbrewer
    - r-rcpp >=1.0
    - r-igraph >=2.2.2

test:
  commands:
    - $R -e "library('multinet')"           # [not win]
    - "\"%R%\" -e \"library('multinet')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=multinet
  license: Apache-2.0
  summary: Functions for the creation/generation and analysis of multilayer social networks <doi:10.18637/jss.v098.i08>.
  license_family: APACHE
  license_file:
    - LICENSE-2.0.txt

extra:
  recipe-maintainers:
    - conda-forge/r
    - agcopenhaver
