{% set version = "4.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-multinet
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/multinet_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/multinet/multinet_{{ version }}.tar.gz
  sha256: c8d7e96f7058bb9e8e7f1ef207d1d3b27cdee079a1112b3512191543ed002be7

build:
  # Checking windows to see if it passes. Uncomment the line if it fails.
  # skip: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcolorbrewer
    - r-rcpp >=1.0.1
    - r-igraph >=1.0.1
  run:
    - r-base
    - r-rcolorbrewer
    - r-rcpp >=1.0.1
    - r-igraph >=1.0.1

test:
  commands:
    - $R -e "library('multinet')"           # [not win]
    - "\"%R%\" -e \"library('multinet')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=multinet
  license: GPL-2.0-or-later
  summary: Functions for the creation/generation and analysis of multilayer social networks.
  license_family: GPL
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - agcopenhaver

# Package: multinet
# Type: Package
# Title: Analysis and Mining of Multilayer Social Networks
# Version: 3.0.3
# Date: 2019-07-13
# Author: Matteo Magnani, Davide Vega, Mikael Dubik (glouvain). The package uses functions from eclat (www.borgelt.net/eclat.html), for association rule mining, Eigen (eigen.tuxfamily.org) and spectra (https://spectralib.org), for matrix manipulation, Infomap (www.mapequation.org), for the Infomap community detection method, and Howard Hinnant's date and time library (https://github.com/HowardHinnant/date). The code from this libraries has been included in our source package.
# Maintainer: Matteo Magnani <matteo.magnani@it.uu.se>
# Description: Functions for the creation/generation and analysis of multilayer social networks.
# License: GPL
# Depends: igraph (>= 1.0.1), Rcpp (>= 1.0.1), methods, RColorBrewer
# LinkingTo: Rcpp
# RcppModules: multinet
# SystemRequirements: A C++14 compiler
# NeedsCompilation: yes
# Repository: CRAN
# Packaged: 2019-07-13 21:42:18 UTC; matteomagnami
# Date/Publication: 2019-07-13 22:40:05 UTC
