appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: Pz3dylWkijIQQ56sn9A1aTrjinF4psi1mJC3MMDeWJyoTh36C9H99AecJUjX66SWytieAgxmuDTvGjZvCa68qYlaUSL2Zw/z6KzBBiBAUQnIPLAVUm/+9y0djmmHmhErw1ShY9Vw6/gXuLjPkXPWZd3qo8doOGLAVmsbm02PX185/t4ybItw8WEE34uQcawQzcaG/sp8gZQpTULA88CVlKemlaLT4a7G73w79AlW66+wx3keaYnhSSdpy1Oe+N1t2vErt65qxCBhJHyWOWId95xxa1qmjhxMA2isalGX08T8PuVPfr2v1TaspRR0Bg9075HrsWR0BAtIqpkBqeoshF+VGpBaOdBSTONKkhVq1lsyrrd57sWcwfIAv1xsVe5WFDuhbPWNP3zwuqve4HtnhCDaHAW0q+Q1RX7fiiu6MqitynwWWcaNvk5MxLC45XMkyjrcMJ5yV0Iq9eQErKBFmsdEzqMbWrx7QPNJZwdqQ5X9h4OxiinPjs7Oto/lEaDvrA+nIA40tHaMn5il6zQQOWD9ol8ujw8L+hwrh/abqiTIFQdu+nGRf/kB0nSZWXRdRqbL7itOwuDJLwHCox6q41MF5ODMXmXGihKl5GcdW2T+QIMq3aNbBu4hOJoz8AIbp3OVq5aHc83as/tmg2V8wvADy6bofO9/Cm40fa2ohBc=
